travis:
  secure:
    BINSTAR_TOKEN: UpQIZC0RDRuRdAp7ohacgbp8f+yoCl92p78DHwfAF5sk6GpOvnNZErR+CE9vKIkJKe+ziHhw4Ufgh5rek4fYq7Qu9pyk43a1VU+nNmV/6/c/atQicIBXSREWo5vkKbwlFi+JeCt3EQJjQidSzCDooczJwRwNIS2/wdEPogC01M+ei0NCNEqFB9XmjrD0pozs8NQ8UOTxyByiLr4lZyLRhTX5RrMbls/+t7REmW30ThVgr0GSbZDQxFEoBs9LGpHMezTPbSYeHwC6RJaSzeA0gLdv3Cjw1I7HqrEIcZuVuj//HQAgrDP6WDgab5CuYiJCcDFAxGZ3XFOl52hXnKmbUh9Xt4MlS+Cu/dBh+5dSPqIMqB9V9OB5JeiUwUD28XRiSEkzL/Q5zQCp0NqGcYMsVqT1BES6eAD/aGI3OSVIBOCvQXyzjWisyhbDFxNsMrZpugu6KojggoofMbZusEm30+G6dO/qTAuZKyYlMDw7k4s6Csh7AX3st+Tz+JDMDWP4bVx1hNMCWiMEb2s9snhR4vbXakgtowLqs2J7GogCUNKwi9fM5e9VXltSxOyEeYjD5lHUCriVGn9qzsHDX9YJfFzYOOZwO8zcPBc1NMHGZTtyXyvebzmUyzLT62PBSJndL0qUhoc6XxTXt5ce6HKxKxgOgOzExSvtmn0WvT20mog=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
